version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: vaasuser
      POSTGRES_PASSWORD: vaaspass
      POSTGRES_DB: vaasdb
      POSTGRES_HOST_AUTH_METHOD : trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./app:/app
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL : postgresql://vaasuser:vaaspass@localhost:5432/vaasdb
      # DATABASE_URL: postgresql+psycopg2://vaasuser:vaaspass@localhost:5432/vaasdb
    depends_on:
      - db
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  superset:
    image: apache/superset:latest
    container_name: superset
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key
      - SUPERSET_DATABASE_URI=postgresql+psycopg2://vaasuser:vaaspass@localhost:5432/vaasdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=1
      - PYTHONPATH=/app/pythonpath
    ports:
      - "8088:8088"
    depends_on:
      - db
      - redis
    command: >
      /bin/bash -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin || true &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088"
    volumes:
      - ~/superset_volumes/duckdb:/app/duckdb


  # Airflow Services
  airflow-webserver:
    image: apache/airflow:2.7.1
    container_name: airflow-webserver
    depends_on:
      - db
      - redis
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://vaasuser:vaaspass@localhost:5432/vaasdb
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://vaasuser:vaaspass@localhost:5432/vaasdb
      - AIRFLOW__CELERY__BROKER_URL=redis://:@redis:6379/0
      - AIRFLOW__CORE__FERNET_KEY=your_fernet_key_here
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.basic_auth
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.7.1
    container_name: airflow-scheduler
    depends_on:
      - db
      - redis
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://vaasuser:vaaspass@localhost:5432/vaasdb
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://vaasuser:vaaspass@localhost:5432/vaasdb
      - AIRFLOW__CELERY__BROKER_URL=redis://:@redis:6379/0
      - AIRFLOW__CORE__FERNET_KEY=your_fernet_key_here
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    restart: always
    command: scheduler

  airflow-worker:
    image: apache/airflow:2.7.1
    container_name: airflow-worker
    depends_on:
      - db
      - redis
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://vaasuser:vaaspass@localhost:5432/vaasdb
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://vaasuser:vaaspass@localhost:5432/vaasdb
      - AIRFLOW__CELERY__BROKER_URL=redis://:@redis:6379/0
      - AIRFLOW__CORE__FERNET_KEY=your_fernet_key_here
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    restart: always
    command: celery worker

  airflow-init:
    image: apache/airflow:2.7.1
    container_name: airflow-init
    depends_on:
      - db
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://vaasuser:vaaspass@localhost:5432/vaasdb
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://vaasuser:vaaspass@localhost:5432/vaasdb
      - AIRFLOW__CELERY__BROKER_URL=redis://:@redis:6379/0
      - AIRFLOW__CORE__FERNET_KEY=your_fernet_key_here
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: version
    restart: "no"

volumes:
  postgres_data: 



networks:
    djangonetwork:
        driver: bridge