version: '3.2'
services:
  test-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5434:5432'  # Changed to avoid conflicts
    volumes:
      - test_postgres_data:/var/lib/postgresql/data

  test-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["pytest", "tests/", "-v", "--tb=short"]
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://testuser:testpass@test-db:5432/testdb
      TESTING: "true"
    depends_on:
      - test-db

volumes:
  test_postgres_data: 